# netlify.toml

[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"

[[redirects]]
  from = "/api/*"
  to = "http://your-api-url/:splat"
  status = 200
  force = true

