[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
